### ISSUE TITLE
Stream Freezing Due to GLib-WARNING: Idle Source Dispatched Without Callback

### ISSUE THREAD

**Issue by alexma233** [games-on-whales/wolf#135]
Description:
I’m experiencing a problem where my stream in a steam container freezes after the following GLib warning appears in the logs:
`
GLib-WARNING **: Idle source dispatched without callback. You must call g_source_set_callback().`

It seems that an idle event source is being dispatched without the necessary callback function. Once this warning occurs, the streaming process halts and cannot continue.

Steps to Reproduce:
1.	Start the streaming process within the steam container.
2.	Wait 2-30 sec.
3.	Monitor logs for the GLib warning.
4.	The stream freezes after the warning is triggered.

Expected Behavior:
The stream should continue smoothly without any interruption, and all idle sources should have the correct callback functions set.

Actual Behavior:
The stream freezes, and no further progress is made after the warning is logged.

**Comment by ABeltramo** [comment]
This has been reported a few times and it seems to be related to the encoding pipeline not being able to push frames "fast" enough. Generally reducing the resolution/bitrate/fps should help.

Could you provide the full Wolf logs and a bit of details on your HW? I suspect the GPU is AMD, right?

**Comment by maxdirocco** [comment]
I am also experiencing this when attempting to stream at my monitor's native resolution and refresh rate (1440p/170Hz).

I am running Wolf on two systems via [Docker Compose](https://games-on-whales.github.io/wolf/stable/user/quickstart.html#_docker):

OS: Arch Linux
GPU: AMD Radeon RX6900XT (vaapi)
CPU: Intel i7 14700k
[amd_arch.log](https://github.com/user-attachments/files/17358276/amd_arch.log)


OS: Truenas Scale 24.10 RC2
GPU: Intel Arc A750 (qsv)
CPU: Intel i7 12700k
[intel_arc_truenas.log](https://github.com/user-attachments/files/17358200/intel_arc_truenas.log)

In both cases, I am not actually able to reach the target 170 FPS at 1440p. The stream generally doesn't exceed 75FPS. Lowering the resolution both increases framerate and reduces freezing.

Please let me know if I can provide any more useful information.
Thanks for your hard work on this!

**Comment by ABeltramo** [comment]
The `GLib-WARNING` and freeze should be fixed with the latest merge, can you try again by updating Wolf using:
```
docker pull ghcr.io/games-on-whales/wolf:stable
```
and restarting Wolf?

Performances shouldn't be affected, if everything went well you'll still have the same FPS as before (we've packed a whole lot of new functionalities under the hood). For AMD I'm looking forward at the Vulkan HW encoders which should improve the performance compared to `vaapi` and they should come soon-ish upstream in Gstreamer.

There are other things that we could definitely improve in Wolf (like implement a 0 copy pipeline) but I'm currently working on other exciting things, like co-op as you can see in the video here: https://github.com/games-on-whales/wolf/pull/101
