### ISSUE TITLE
Setting a different dir than /etc/wolf behaves oddly

### ISSUE THREAD

**Issue by duskmoss** [games-on-whales/wolf#67]
In order to successfully use a different dir you  need to change all three places. 

``` 
- HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - /etc/wolf/:/etc/wolf 
```

has to become 
``` 
- HOST_APPS_STATE_FOLDER=/var/mnt/otherdrive/wolf
    volumes:
      - /var/mnt/otherdrive/wolf/:/var/mnt/otherdrive/wolf 
```

If you just change the local folder mounted to the volume it appears containers spawned by wolf still look in /etc/wolf. So you need to change HOST_APPS_STATE_FOLDER.  But then the main container has that mounted to /etc/wolf so you need to change that too. 

I feel like if the sub containers can't be automatically setup to copy the volume logic of the main container it should be a variable used 3 times in the docker command/compose file. Or at least document this behavior. 

(thanks so much btw I was looking at sunshine thinking there has to be a way to make all this headless and here we are)

**Comment by ABeltramo** [comment]
This should definitely be documented better in the docs; it's a bit tricky to get automatically since:
- Wolf being in charge of running additional containers needs to know which folder on the host should be volume mounted (`HOST_APPS_STATE_FOLDER`)
- Additionally it needs to add some files that will be shared between Wolf and the running app in order to implement proper hotplug. In order to do that it defaults to `$HOST_APPS_STATE_FOLDER/...path..` but since Wolf runs inside a docker container itself it needs to have access to that path

I don't exclude that we could get clever and use volumes instead of paths on the host in future but I think it's fairly clean and easy as it is now.

**Comment by ABeltramo** [comment]
This has been added to the docs: https://games-on-whales.github.io/wolf/stable/user/configuration.html#_change_the_host_apps_state_folder

Closing this.
